### ISSUE TITLE
Fontの設定

### ISSUE THREAD

**Issue by Umigishi-Aoi** [project-gemini-by-fluttter-univ/gemini-app#33]
M PLUS 1のフォントを全体に設定してください。

参考：https://zenn.dev/susatthi/articles/20220419-143426-flutter-custom-fonts

**Comment by ntsts03** [comment]
質問です。
上のURLのこちらについてです。
`void main() {
  runApp(const GeminiApp());
}`
から、main.dartの構成を弄らないと出来ない気がしますがどうでしょうか？

<img width="500" alt="スクリーンショット 2024-09-16 14 28 32" src="https://github.com/user-attachments/assets/c9e8ee96-f26f-41a9-b97d-eb50d6906e4d">

**Comment by ntsts03** [comment]
一旦自分でやってみます

**Comment by Umigishi-Aoi** [comment]
プルリクに返答します！
